POST http://localhost:5000/duels
Content-Type: application/json

{
  "ranges": {
    "1": {
      "classes": {
        "S": {
          "participants": [
            "Orest Voloshchuk",
            "Oleksandr Rogozin",
            "Denys Yuzvyk",
            "Oleksandr Remez",
            "Roman Vynar"
          ],
          "twice": false
        },
        "SM": {
          "participants": [
            "Yevgen Moroz",
            "Anton Laskavyy",
            "Viktor Kozachenko"
          ],
          "twice": true
        }
      }
    },
    "2": {
      "classes": {
        "SL": {
          "participants": [
            "Victoria Papa",
            "Iryna Skyts",
            "Anastasiia Matsekh",
            "Sofiia Lysiuk"
          ],
          "twice": true
        }
      }
    }
  }
}

### Failing request
POST http://localhost:5000/duels
Content-Type: application/json

{
  "ranges": {
    "1": {
      "classes": {
        "S": {
          "participants": [
            "Волощук",
            "Рогозін",
            "Шатєєв",
            "Ремез",
            "Вострес",
            "Папа",
            "Козаченко"
          ],
          "twice": false
        }
      }
    },
    "2": {
      "classes": {}
    }
  }
}

###
POST http://localhost:5000/duels/excel
Content-Type: application/json

{
  "ranges": {
    "1": {
      "classes": {
        "S": {
          "participants": [
            "Orest Voloshchuk",
            "Oleksandr Rogozin",
            "Denys Yuzvyk",
            "Oleksandr Remez",
            "Roman Vynar"
          ],
          "twice": false
        },
        "SM": {
          "participants": [
            "Yevgen Moroz",
            "Anton Laskavyy",
            "Viktor Kozachenko"
          ],
          "twice": true
        }
      }
    },
    "2": {
      "classes": {
        "SL": {
          "participants": [
            "Victoria Papa",
            "Iryna Skyts",
            "Anastasiia Matsekh",
            "Sofiia Lysiuk"
          ],
          "twice": true
        }
      }
    }
  }
}
